# Generated by Django 6.0.3 on 2026-09-30 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=512)),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('document_id', models.CharField(help_text='Stable document identifier derived from the filename.', max_length=512)),
                ('document_revision', models.CharField(default='1', max_length=64)),
                ('asset_id', models.CharField(blank=True, help_text='Free-text asset reference (validated at the API layer).', max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('parsing', 'Parsing'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('stored', 'Stored'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('chunk_count', models.PositiveIntegerField(blank=True, null=True)),
                ('config_version', models.CharField(default='v1-2026-09-29', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_job',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_sha256', 'document_revision', 'config_version'), name='uniq_ingestion_job_source_revision_config')],
            },
        ),
    ]
