# Generated by Django 6.0.3 on 2026-10-02 04:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("doc_key", models.CharField(max_length=128, unique=True)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("document_revision", models.CharField(default="1", max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("parse_error", models.TextField(blank=True, default="")),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rag_status",
                    models.CharField(
                        choices=[
                            ("none", "Not generated"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "rag_strategy",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("rag_params", models.JSONField(blank=True, default=dict)),
                ("rag_chunk_count", models.PositiveIntegerField(default=0)),
                ("rag_error", models.TextField(blank=True, default="")),
                ("rag_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "graph_status",
                    models.CharField(
                        choices=[
                            ("none", "Not generated"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "library_document",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("parse", "Parse"), ("embed", "Generate embeddings")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("progress_done", models.PositiveIntegerField(default=0)),
                ("progress_total", models.PositiveIntegerField(default=0)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("error", models.TextField(blank=True, default="")),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="ingestion.document",
                    ),
                ),
            ],
            options={
                "db_table": "library_job",
                "ordering": ["created_at"],
            },
        ),
    ]
