# Generated by Django 6.0.3 on 2026-10-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_document_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="graph_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="graph_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="kind",
            field=models.CharField(
                choices=[
                    ("parse", "Parse"),
                    ("embed", "Generate embeddings"),
                    ("extract", "Generate triples"),
                ],
                max_length=16,
            ),
        ),
    ]
