# Generated by Django 6.0.3 on 2026-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0003_extraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="figures_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="figures_status",
            field=models.CharField(
                choices=[
                    ("none", "Not described"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("pending", "Visual interpretation pending"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="figures_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="run_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="kind",
            field=models.CharField(
                choices=[
                    ("parse", "Parse"),
                    ("embed", "Generate embeddings"),
                    ("extract", "Generate triples"),
                    ("figures", "Describe figures"),
                ],
                max_length=16,
            ),
        ),
    ]
