# Generated by Django 6.0.3 on 2026-10-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("purpose", models.CharField(db_index=True, max_length=20)),
                ("model_id", models.CharField(max_length=128)),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "completion_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("tokens_estimated", models.BooleanField(default=False)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
