"""
Django settings for neo_llm_api project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Must be set via DJANGO_SECRET_KEY in .env — never hardcode here.
_secret_key = os.getenv("DJANGO_SECRET_KEY")
if not _secret_key:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Add it to your .env file.\n"
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
"127.0.0.1",
"localhost",
"100.92.170.72", # Tailscale IP you use from your PC
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ## Third party
    "rest_framework",
    "corsheaders",
    # Local apps
    "chat",
    "historian",
    "context_graph",
    "ingestion",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'neo_llm_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'neo_llm_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },

     "historian": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("HIST_DB_NAME", "plc_1_historian"),
        "USER": os.getenv("HIST_DB_USER", "plc_1_historian_user"),
        "PASSWORD": os.getenv("HIST_DB_PASSWORD", "test1234"),
        "HOST": os.getenv("HIST_DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("HIST_DB_PORT", "5432"),
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database routers
DATABASE_ROUTERS = [
    "neo_llm_api.db_routers.HistorianRouter",
]


# === External GPT (Grok / xAI) config ===
GROK_API_BASE = os.getenv("GROK_API_BASE", "https://api.x.ai/v1")
GROK_API_KEY = os.getenv("GROK_API_KEY", "")
GROK_CHAT_MODEL = os.getenv("GROK_CHAT_MODEL", "grok-4-fast-reasoning")

# === DGX Spark / vLLM backend (Qwen3.8-27B-FP8, main LLM :8004) ===
DGX_API_BASE = os.getenv("DGX_API_BASE", "http://100.74.225.3:8004")
DGX_CHAT_MODEL = os.getenv("DGX_CHAT_MODEL", "qwen38-27b-fp8")
# RAG shared infra on DGX (Tailscale IP 100.74.225.3 = spark-ec99)
DGX_EMBED_URL = os.getenv("DGX_EMBED_URL", "http://100.74.225.3:8010/v1/embeddings")
DGX_EMBED_MODEL = os.getenv("DGX_EMBED_MODEL", "nemotron-3-embed-1b")
DGX_RERANK_URL = os.getenv("DGX_RERANK_URL", "http://100.74.225.3:8011/rerank")
DGX_RERANK_MODEL = os.getenv("DGX_RERANK_MODEL", "llama-nemotron-rerank-1b-v2")

# === BSK Ingestion (Phase 4) ===
# Docling Serve on the BSK ingestion desktop (Tailscale, single-worker).
DOCLING_URL = os.getenv("DOCLING_URL", "http://100.86.26.4:5001")
# Raw uploads land in incoming/; parsed outputs are archived to processed/.
INGESTION_RAW_BASE = os.getenv(
    "INGESTION_RAW_BASE", str(BASE_DIR / "data" / "incoming")
)
INGESTION_OUTPUT_BASE = os.getenv(
    "INGESTION_OUTPUT_BASE", str(BASE_DIR / "data" / "processed")
)
# Bump whenever chunker/embedding config changes — part of the idempotency key.
# v2: real page numbers, paragraph/table/list content types, Docling image placeholders.
INGESTION_CONFIG_VERSION = os.getenv("INGESTION_CONFIG_VERSION", "v2-2026-10-01")
# In-flight jobs older than this are treated as dead (e.g. the worker thread was
# killed by a runserver reload) and re-run on re-upload.
INGESTION_STALE_MINUTES = int(os.getenv("INGESTION_STALE_MINUTES", "30"))
# Clean-start Chroma collection for v2 ingestion.
RAG_COLLECTION_V2 = os.getenv("RAG_COLLECTION_V2", "bsk_rag_v2")

# === Chat context window ===
# Max prior messages (user + assistant) sent to the model with each turn.
CHAT_HISTORY_MAX_MESSAGES = int(os.getenv("CHAT_HISTORY_MAX_MESSAGES", "20"))
# Total prompt budget in characters (~4 chars per token): system prompt (incl.
# RAG context) + history + current message. History gets what is left after
# the system prompt and current message, oldest messages dropped first.
CHAT_CONTEXT_MAX_CHARS = int(os.getenv("CHAT_CONTEXT_MAX_CHARS", "24000"))
# Ollama defaults to a ~4k-token context and silently truncates the start of
# the prompt on overflow, so keep its budget small.
CHAT_CONTEXT_MAX_CHARS_OLLAMA = int(os.getenv("CHAT_CONTEXT_MAX_CHARS_OLLAMA", "6000"))


# === Logging ===
LOG_DIR = Path(os.getenv("LOG_DIR", str(BASE_DIR / "logs")))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "standard"},
        "chat_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "chat.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "standard",
        },
    },
    "loggers": {
        "chat": {"handlers": ["console", "chat_file"], "level": "INFO", "propagate": False},
    },
}


# === RAG v2 retrieval (bsk_rag_v2 + DGX reranker) ===
# Chroma: server mode when CHROMA_HOST is set (required with the library worker —
# embedded mode isn't process-safe); CHROMA_DIR is the data folder (mounted into
# the server container, or opened directly in embedded mode for tests).
CHROMA_HOST = os.getenv("CHROMA_HOST", "")
CHROMA_PORT = int(os.getenv("CHROMA_PORT", "8100"))
CHROMA_DIR = os.getenv(
    "CHROMA_DIR", "/home/barajas_angel/repos/BSK.AI.Local_LLM_neo4j-graphrag/data/chroma_index"
)
# Vector-search candidates passed to the reranker.
RAG_V2_CANDIDATES = int(os.getenv("RAG_V2_CANDIDATES", "20"))
# Chunks kept after reranking for chat context (before the context budget cap).
RAG_CHAT_TOP_N = int(os.getenv("RAG_CHAT_TOP_N", "5"))
# Default top_k on /api/rag/query/ (RAG Lab Top-K slider marker).
RAG_QUERY_DEFAULT_TOP_K = int(os.getenv("RAG_QUERY_DEFAULT_TOP_K", "5"))
# Upper bound for top_k on /api/rag/query/ (RAG Lab Top-K slider).
RAG_QUERY_MAX_TOP_K = int(os.getenv("RAG_QUERY_MAX_TOP_K", "10"))
# Share of the model's CHAT_CONTEXT_MAX_CHARS* budget that RAG context may use;
# history gets what is left.
RAG_CONTEXT_SHARE = float(os.getenv("RAG_CONTEXT_SHARE", "0.5"))
# Reranker request timeout (seconds); on timeout we fall back to vector order.
RAG_RERANK_TIMEOUT = float(os.getenv("RAG_RERANK_TIMEOUT", "10"))
# Chat drops reranked chunks scoring below this (reranker scores are ~0.0 for
# unrelated text, 0.6+ for relevant). Not applied when the reranker fell back,
# nor to the RAG Lab debugger.
RAG_MIN_RERANK_SCORE = float(os.getenv("RAG_MIN_RERANK_SCORE", "0.1"))


# === Conversation titles ===
# Timeout (seconds) for the one-off DGX call that titles a new conversation;
# on timeout the title falls back to the start of the first message.
CHAT_TITLE_TIMEOUT = float(os.getenv("CHAT_TITLE_TIMEOUT", "6"))


# === Context Graph (Neo4j) ===
# Optional: with GRAPH_ENABLED=false the app runs without Neo4j.
# Start the dedicated instance: docker compose -f deploy/neo4j/docker-compose.yml --env-file .env up -d
GRAPH_ENABLED = os.getenv("GRAPH_ENABLED", "false").lower() == "true"
NEO4J_URI = os.getenv("NEO4J_URI", "bolt://127.0.0.1:7687")
NEO4J_USER = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "")
NEO4J_DATABASE = os.getenv("NEO4J_DATABASE", "neo4j")
NEO4J_CONNECTION_TIMEOUT = float(os.getenv("NEO4J_CONNECTION_TIMEOUT", "5"))


# === Document library (shared by RAG Lab and GraphLab) ===
# Uploaded files and cached Docling output live under LIBRARY_BASE/<document id>/.
LIBRARY_BASE = os.getenv("LIBRARY_BASE", str(BASE_DIR / "data" / "library"))
# Running jobs whose heartbeat is older than this are re-queued by the worker.
LIBRARY_JOB_STALE_SECONDS = int(os.getenv("LIBRARY_JOB_STALE_SECONDS", "300"))
# Max upload size per file (bytes).
LIBRARY_MAX_UPLOAD_BYTES = int(os.getenv("LIBRARY_MAX_UPLOAD_BYTES", str(200 * 1024 * 1024)))


# Tests never touch the live Chroma server (see neo_llm_api/test_runner.py).
TEST_RUNNER = "neo_llm_api.test_runner.IsolatedTestRunner"


# === GraphLab triple extraction (DGX) ===
GRAPH_EXTRACT_TIMEOUT = float(os.getenv("GRAPH_EXTRACT_TIMEOUT", "120"))       # seconds per window call
GRAPH_EXTRACT_MAX_TOKENS = int(os.getenv("GRAPH_EXTRACT_MAX_TOKENS", "2000"))  # output budget per window
