"""
Django settings for neo_llm_api project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Must be set via DJANGO_SECRET_KEY in .env — never hardcode here.
_secret_key = os.getenv("DJANGO_SECRET_KEY")
if not _secret_key:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Add it to your .env file.\n"
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
"127.0.0.1",
"localhost",
"100.92.170.72", # Tailscale IP you use from your PC
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ## Third party
    "rest_framework",
    "corsheaders",
    # Local apps
    "chat",
    "historian",
    "ingestion",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'neo_llm_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'neo_llm_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },

     "historian": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("HIST_DB_NAME", "plc_1_historian"),
        "USER": os.getenv("HIST_DB_USER", "plc_1_historian_user"),
        "PASSWORD": os.getenv("HIST_DB_PASSWORD", "test1234"),
        "HOST": os.getenv("HIST_DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("HIST_DB_PORT", "5432"),
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database routers
DATABASE_ROUTERS = [
    "neo_llm_api.db_routers.HistorianRouter",
]


# === External GPT (Grok / xAI) config ===
GROK_API_BASE = os.getenv("GROK_API_BASE", "https://api.x.ai/v1")
GROK_API_KEY = os.getenv("GROK_API_KEY", "")
GROK_CHAT_MODEL = os.getenv("GROK_CHAT_MODEL", "grok-4-fast-reasoning")

# === DGX Spark / vLLM backend (Qwen3.8-27B-FP8, main LLM :8004) ===
DGX_API_BASE = os.getenv("DGX_API_BASE", "http://100.74.225.3:8004")
DGX_CHAT_MODEL = os.getenv("DGX_CHAT_MODEL", "qwen38-27b-fp8")
# RAG shared infra on DGX (Tailscale IP 100.74.225.3 = spark-ec99)
DGX_EMBED_URL = os.getenv("DGX_EMBED_URL", "http://100.74.225.3:8010/v1/embeddings")
DGX_EMBED_MODEL = os.getenv("DGX_EMBED_MODEL", "nemotron-3-embed-1b")
DGX_RERANK_URL = os.getenv("DGX_RERANK_URL", "http://100.74.225.3:8011/rerank")
DGX_RERANK_MODEL = os.getenv("DGX_RERANK_MODEL", "llama-nemotron-rerank-1b-v2")

# === BSK Ingestion (Phase 4) ===
# Docling Serve on the BSK ingestion desktop (Tailscale, single-worker).
DOCLING_URL = os.getenv("DOCLING_URL", "http://100.86.26.4:5001")
# Raw uploads land in incoming/; parsed outputs are archived to processed/.
INGESTION_RAW_BASE = os.getenv(
    "INGESTION_RAW_BASE", str(BASE_DIR / "data" / "incoming")
)
INGESTION_OUTPUT_BASE = os.getenv(
    "INGESTION_OUTPUT_BASE", str(BASE_DIR / "data" / "processed")
)
# Bump whenever chunker/embedding config changes — part of the idempotency key.
INGESTION_CONFIG_VERSION = os.getenv("INGESTION_CONFIG_VERSION", "v1-2026-09-29")
# Clean-start Chroma collection for v2 ingestion.
RAG_COLLECTION_V2 = os.getenv("RAG_COLLECTION_V2", "bsk_rag_v2")