# Generated by Django 6.0.3 on 2026-04-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
