# Generated by Django 6.0.3 on 2026-10-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_model_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
