# Generated by Django 6.0.3 on 2026-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="asset_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
