# Generated by Django 6.0.3 on 2026-10-02 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context_graph", "0001_initial"),
        ("ingestion", "0003_extraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("schema", "Schema-guided"),
                            ("freeform", "Free-form"),
                        ],
                        max_length=16,
                    ),
                ),
                ("template", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["mode", "name"],
            },
        ),
        migrations.CreateModel(
            name="CandidateTriple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("schema", "Schema-guided"),
                            ("freeform", "Free-form"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        blank=True,
                        choices=[("curated", "Curated"), ("lab", "Lab")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("subject_name", models.CharField(max_length=255)),
                ("subject_type", models.CharField(max_length=100)),
                (
                    "subject_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("subject_existing", models.BooleanField(default=False)),
                ("predicate", models.CharField(max_length=100)),
                ("object_name", models.CharField(max_length=255)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, default="", max_length=512)),
                ("object_existing", models.BooleanField(default=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("issue", models.CharField(blank=True, default="", max_length=255)),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("page_start", models.PositiveIntegerField(blank=True, null=True)),
                ("page_end", models.PositiveIntegerField(blank=True, null=True)),
                ("section_path", models.JSONField(blank=True, default=list)),
                ("evidence_text", models.TextField(blank=True, default="")),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                (
                    "preset_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("preset_version", models.PositiveIntegerField(blank=True, null=True)),
                ("schema_version", models.PositiveIntegerField(blank=True, null=True)),
                ("edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triples",
                        to="ingestion.document",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triples",
                        to="ingestion.job",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "chunk_index", "id"],
                "indexes": [
                    models.Index(
                        fields=["document", "status"],
                        name="context_gra_documen_8a46e8_idx",
                    )
                ],
            },
        ),
    ]
