# Generated by Django 6.0.3 on 2026-10-02 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context_graph", "0002_extraction"),
        ("ingestion", "0003_extraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("kind", models.CharField(max_length=8)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("sheets", models.JSONField(blank=True, default=list)),
                ("sheet", models.CharField(blank=True, default="", max_length=255)),
                ("header_row", models.PositiveIntegerField(default=1)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("asset_id", models.CharField(blank=True, default="", max_length=512)),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("staged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("mapping", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="applied_props",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="object_props",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="row_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="source",
            field=models.CharField(
                choices=[
                    ("text", "Extracted from text"),
                    ("structured", "Structured import"),
                ],
                default="text",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="subject_props",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="candidatetriple",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triples",
                to="ingestion.document",
            ),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="data_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triples",
                to="context_graph.datafile",
            ),
        ),
        migrations.AddIndex(
            model_name="candidatetriple",
            index=models.Index(
                fields=["data_file", "status"], name="context_gra_data_fi_376bb6_idx"
            ),
        ),
    ]
