# Generated by Django 6.0.3 on 2026-10-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context_graph", "0003_structured_import"),
        ("ingestion", "0003_extraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatetriple",
            name="applied_aliases",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("text", "Document text"),
                            ("structured", "Structured import"),
                            ("vision", "Vision (VLM)"),
                            ("human", "Human"),
                            ("opc", "OPC UA"),
                        ],
                        max_length=16,
                    ),
                ),
                ("page_start", models.PositiveIntegerField(blank=True, null=True)),
                ("page_end", models.PositiveIntegerField(blank=True, null=True)),
                ("section_path", models.JSONField(blank=True, default=list)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("region", models.JSONField(blank=True, default=dict)),
                ("figure_id", models.CharField(blank=True, default="", max_length=64)),
                ("chunk_index", models.PositiveIntegerField(blank=True, null=True)),
                ("window", models.JSONField(blank=True, default=dict)),
                ("extractor", models.CharField(blank=True, default="", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("prompt", models.CharField(blank=True, default="", max_length=120)),
                ("schema_version", models.PositiveIntegerField(blank=True, null=True)),
                ("excerpt", models.TextField(blank=True, default="")),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="context_graph.datafile",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="ingestion.document",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="evidence",
            field=models.ManyToManyField(
                blank=True, related_name="triples", to="context_graph.evidence"
            ),
        ),
    ]
