# Generated by Django 6.0.3 on 2026-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context_graph", "0005_backfill_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatetriple",
            name="object_candidates",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="object_match",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="subject_candidates",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="candidatetriple",
            name="subject_match",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
