# Generated by Django 6.0.3 on 2026-04-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlcSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('ts', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('quality', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'plc_signals',
                'ordering': ['-ts'],
            },
        ),
    ]
