# Generated by Django 6.0.3 on 2026-04-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtruderSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('extruder_id', models.CharField(max_length=30)),
                ('batch_id', models.CharField(max_length=50)),
                ('recipe_id', models.CharField(max_length=50)),
                ('shift_code', models.CharField(max_length=10)),
                ('machine_state', models.CharField(max_length=20)),
                ('screw_speed_rpm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screw_torque_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motor_power_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder_rate_actual_kg_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barrel_zone_1_temp_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barrel_zone_2_temp_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barrel_zone_3_temp_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('head_temp_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('steam_flow_kg_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_injection_l_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('die_pressure_bar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_temp_discharge_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_moisture_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bulk_density_g_l', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kibble_diameter_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('throughput_actual_kg_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('throughput_target_kg_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('good_output_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scrap_output_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('downtime_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('performance_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quality_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oee_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alarm_active', models.BooleanField(default=False)),
                ('alarm_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'extruder_samples',
                'ordering': ['-ts'],
            },
        ),
        migrations.DeleteModel(
            name='PlcSignal',
        ),
    ]
